READ*,MARKS
IF(MARKS>=80)THEN
    PRINT*,"A+"
ELSE IF(MARKS>=75)THEN
    PRINT*,"A"
ELSE IF(MARKS>=70)THEN
    PRINT*,"A-"
ELSE IF(MARKS>=65)THEN
    PRINT*,"B+"
ELSE IF(MARKS>=60)THEN
    PRINT*,"B"
ELSE IF(MARKS>=55)THEN
    PRINT*,"B-"
ELSE IF(MARKS>=50)THEN
    PRINT*,"C+"
ELSE IF(MARKS>=45)THEN
    PRINT*,"C"
ELSE IF(MARKS>=40)THEN
    PRINT*,"D"
ELSE
    PRINT*,"FAIL"
END IF
END
