DIMENSION G(100)
PRINT*,"INPUT THE NUMBER OF DATA"
READ*,N
AN=0.0
VAR=0.0
AB=0.0
DO I=1,N
    READ*,G(I)
    AN=AN+G(I)/N
    VAR=VAR+G(I)*G(I)

END DO
PRINT*,"MEAN=",AN
PRINT*,"STD=",SQRT((VAR/N)-(AN)**2)
DO I=1,N
    AB=AB+ABS(G(I)-AN)
END DO
PRINT*,"ABSULATE MEAN DEV= ",AB/N
END
