PRINT*,"INPUT 1  FOR F TO C, OR 2  FOR C TO F"
READ*,OPTION
READ*,TEM
IF(OPTION==1)PRINT*,"TEMPERATURE IN CELCIUS=",(TEM-32)/1.8
IF(OPTION==2)PRINT*,"TEMPERATURE IN FARENHAIT=",32+1.8*TEM
END

