READ*,MARK
IF(MARK>=80)THEN
    PRINT*,"A+"
ELSE IF(MARK>=75)THEN
    PRINT*,"A"
ELSE IF(MARK>=70)THEN
    PRINT*,"A-"
ELSE IF(MARK>=65)THEN
    PRINT*,"B+"
ELSE IF(MAKR>=60)THEN
    PRINT*,"B"
ELSE IF(MAKR>=55)THEN
    PRINT*,"B-"
ELSE IF(MARK>=50)THEN
    PRINT*,"C+"
ELSE IF(MAKR>=45)THEN
    PRINT*,"C"
ELSE IF(MARK>=40)THEN
    PRINT*,"D"
ELSE
    PRINT*,"FAIL"
END IF
END
